config/routes.rb
Rails.application.routes.draw do

  resources :polls
  resources :candidates
  get 'candidates/new/:poll_id'   => 'candidates#new', as: :new_poll_candidate

  get 'admin/index'               => 'admin#index', as: :admin
  get 'admin/ban/:id'             => 'admin#ban', as: :ban
  get 'admin/release/:id'         => 'admin#release', as: :release
  get 'admin/makeAdmin/:id'       => 'admin#makeAdmin', as: :make_admin
  get 'admin/makeNormal/:id'      => 'admin#makeNormal', as: :make_normal
  get 'admin/makeManager/:id'     => 'admin#makeManager', as: :make_manager
  delete 'admin/destroy/:id'      => 'admin#destroy', as: :destroy

  devise_for :users

  root 'election#index'
  get 'election/index'
  get 'election/view/:poll_id'      => 'election#view', as: :election_view
  get 'election/vote/:candidate_id' => 'election#vote', as: :vote

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  belongs_to :poll
  has_many :votes
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :candidates, dependent: :destroy
  has_many :votes

  belongs_to :creator, class_name: 'User'
end

app/models/role.rb
class Role < ActiveRecord::Base
  # example:  Role.first.users.first.departments
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable, :rememberable, :trackable

  has_many :polls, foreign_key: 'creator_id', dependent: :destroy
  has_many :votes

  belongs_to :role

  def admin?
    self.role_id == 2
  end

  def normal?
    self.role_id == 1
  end

  def manager?
    self.role_id == 3
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :user
  belongs_to :poll
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :set_user, only: [:destroy, :makeAdmin, :makeNormal, :makeManager, :ban, :release]
  before_filter :authenticate_admin_user!

  def index
    @users = User.all
    @admins = User.where(role_id: 2)
    @managers = User.where(role_id: 3)
  end

  def ban
    @user.update(banned: true)
    flash[:notice] = "User sucessfully banned."
    redirect_to admin_path
  end

  def release
    @user.update(banned: false)
    flash[:notice] = "User sucessfully released."
    redirect_to admin_path
  end

  def makeAdmin
    @user.update(role_id: 2)
    redirect_to admin_path
  end

  def makeNormal
    @user.update(role_id: 1)
    redirect_to admin_path
  end

  def makeManager
    @user.update(role_id: 3)
    redirect_to admin_path
  end

  def destroy
    @user.destroy
    flash[:notice] = "User sucessfully destroyed."
    redirect_to admin_path
  end

  private
  def set_user
    @user = User.find(params[:id]) if params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin_user!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "This area is restricted to administrators only."
      redirect_to root_path
    end
  end

  def authenticate_manager_user!
    authenticate_user!
    unless current_user.manager?
      flash[:alert] = "This area is restricted to managers only."
      redirect_to root_path
    end
  end

  def current_admin_user
    return nil if user_signed_in? && !current_user.admin?
    current_user
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]
  before_action :set_poll, only: [:new  ]

  before_filter :authenticate_manager_user!, except: [:index, :show]
  respond_to :html

  def index
    @candidates = Candidate.all
    respond_with(@candidates)
  end

  def show
    respond_with(@candidate)
  end

  def new
    if @poll.creator == current_user
      @candidate = Candidate.new
      @candidate.poll = @poll
      respond_with(@candidate)
    else
      flash[:alert] = "This area is restricted to creator only."
      redirect_to(:back)
    end
  end

  def edit
    if @candidate.poll.creator != current_user
      flash[:alert] = "This area is restricted to creator only."
      redirect_to(:back)
    end
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.poll.creator == current_user
      @candidate.save
      respond_with(@candidate)
    else
      flash[:alert] = "You can only add candidates from your polls."
      redirect_to(:back)
    end
  end

  def update
    if @candidate.poll.creator == current_user
      @candidate.update(candidate_params)
      respond_with(@candidate)
    else
      flash[:alert] = "You can only update candidates from your polls."
      redirect_to(:back)
    end
  end

  def destroy
    if @candidate.poll != nil and @candidate.poll.creator == current_user
      @candidate.destroy
      respond_with(@candidate)
    else
      flash[:alert] = "You can only destroy candidates from your polls."
      redirect_to(:back)
    end
  end

  private
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    def candidate_params
      params.require(:candidate).permit(:name, :description, :poll_id, :link1, :link2)
    end

    def set_poll
      @poll = Poll.find(params[:poll_id])
    end
end

app/controllers/election_controller.rb
class ElectionController < ApplicationController
  before_action :set_poll, only: [:view]
  before_filter :authenticate_user!, except: [:index]

  respond_to :html
  def index
    @polls = Poll.all
  end

  def view

  end

  def vote

    if (!isStudent(current_user.login))
      flash[:alert] = "This poll is only for students."
      redirect_to election_view_path(@poll) and return
    end

    @candidate = Candidate.find(params[:candidate_id])
    @poll = @candidate.poll

    current_user.votes.each do |vote|
      if vote.poll == @poll
        flash[:alert] = "You have already voted."
        redirect_to election_view_path(@poll) and return
      end
    end

    vote = Vote.new(user: current_user, candidate: @candidate, poll: @poll)
    if vote.save and (@poll.update(participants: @poll.participants+1))
      flash[:notice] = "Your vote has been sucessfully recorded."
      UserMailer.voted(current_user, @poll).deliver
    else
      flash[:alert] = "Your vote has failed. Please contact Admin."
    end
    redirect_to election_view_path(@poll)
  end


  private
    def set_poll
      @poll = Poll.find(params[:poll_id])
    end

    def isStudent(id)
      return id.match(/[s][t]\d{6,}/) != nil
    end

    def is_number?
      self.to_f.to_s == self.to_s || self.to_i.to_s == self.to_s
    end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_manager_user!, except: [:index]
  respond_to :html

  def index
    @polls = Poll.all
    respond_with(@polls)
  end

  def show
    @candidates = @poll.candidates
    respond_with(@poll)
  end

  def new
    @poll = Poll.new
    respond_with(@poll)
  end

  def edit
    if @poll.creator != current_user
      flash[:alert] = "You can only update your polls."
      redirect_to(polls_path)
    end
  end

  def create
    @poll = Poll.new(poll_params)
    @poll.creator = current_user
    @poll.save
    UserMailer.poll_created(current_user, @poll).deliver
    respond_with(@poll)
  end

  def update
    if @poll.creator == current_user
      @poll.update(poll_params)
    else
      flash[:alert] = "You can only update your polls."
    end
    respond_with(@poll)
  end

  def destroy
    if @poll.creator == current_user
      @poll.destroy
    else
      flash[:alert] = "You can only destroy your polls."
    end
    respond_with(@poll)
  end

  private
    def set_poll
      @poll = Poll.find(params[:id])
    end

    def poll_params
      params.require(:poll).permit(:title, :description, :start, :end, :participants)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/election_helper.rb
module ElectionHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/admin/_admins.html.erb
<h2>List of <b>ADMINS</b></h2>
<table width="100%" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |user| %>
    <tr>
      <td><%= user.login %></td>
      <td><%= user.role.name %></td>
      <td><%= user.email %></td>

      <td><%= link_to 'Make Normal', make_normal_path(user) %></td>
      <td><%= link_to 'Make Manager', make_manager_path(user) %></td>

      <% if current_user.login != user.login %>
      <% if user.banned %>
      <td><%= link_to 'Release', release_path(user) %></td>
      <% else%>
      <td><%= link_to 'Ban', ban_path(user) %></td>

      <% end %>
      <td><%= link_to 'Destroy', '#', method: :delete,
      data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/_managers.html.erb
<h2>List of <b>MANAGERS</b></h2>
<table width="100%" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |user| %>
    <tr>
      <td><%= user.login %></td>
      <td><%= user.role.name %></td>
      <td><%= user.email %></td>

      <td><%= link_to 'Make Normal', make_normal_path(user) %></td>
      <td><%= link_to 'Make Admin', make_admin_path(user) %></td>

      <% if current_user.login != user.login %>
      <% if user.banned %>
      <td><%= link_to 'Release', release_path(user) %></td>
      <% else%>
      <td><%= link_to 'Ban', ban_path(user) %></td>

      <% end %>
      <td><%= link_to 'Destroy', destroy_path(user), method: :delete,
      data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/_normals.html.erb
<h2>All <b>USERS</b></h2>
<table width="100%" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.login %></td>
      <td><%= user.role.name %></td>
      <td><%= user.email %></td>

      <% if user.role_id == 2 %>
        <td><%= link_to 'Make Normal', make_normal_path(user) %></td>
        <td><%= link_to 'Make Manager', make_manager_path(user) %></td>
      <% elsif user.role_id == 3 %>
        <td><%= link_to 'Make Normal', make_normal_path(user) %></td>
        <td><%= link_to 'Make Admin', make_admin_path(user) %></td>
      <% else %>
        <td><%= link_to 'Make Admin', make_admin_path(user) %></td>
        <td><%= link_to 'Make Manager', make_manager_path(user) %></td>
      <% end %>
      <% if current_user.login != user.login %>
        <% if user.banned %>
          <td><%= link_to 'Release', release_path(user) %></td>
        <% else%>
          <td><%= link_to 'Ban', ban_path(user) %></td>

        <% end %>
        <td><%= link_to 'Destroy', destroy_path(user), method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/ban.html.erb
<h1>Admin#ban</h1>
<p>Find me in app/views/admin/ban.html.erb</p>

app/views/admin/destroy.html.erb
<h1>Admin#destroy</h1>
<p>Find me in app/views/admin/destroy.html.erb</p>

app/views/admin/index.html.erb
<div id="admins" class="jumbotron">
  <%= render 'admins' %>
</div>

<div id="managers" class="jumbotron">
  <%= render 'managers' %>
</div>

<div id="normals" class="jumbotron">
  <%= render 'normals' %>
</div>

app/views/admin/makeAdmin.html.erb
<h1>Admin#makeAdmin</h1>
<p>Find me in app/views/admin/makeAdmin.html.erb</p>

app/views/admin/makeManager.html.erb
<h1>Admin#makeManager</h1>
<p>Find me in app/views/admin/makeManager.html.erb</p>

app/views/admin/makeNormal.html.erb
<h1>Admin#makeNormal</h1>
<p>Find me in app/views/admin/makeNormal.html.erb</p>

app/views/candidates/_form.html.erb
<div class="jumbotron">
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :poll_id, class: "control-label" %>
    <div>
      <%= f.hidden_field :poll_id, class: "form-control" %>
      <%= label 'poll', @candidate.poll.title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :name, class: "control-label" %>
    <div><%= f.text_field :name, class: "form-control" %></div>
  </div>

  <div class="form-group field">
    <%= f.label :description, class: "control-label" %>
    <div><%= f.text_area :description, class: "form-control", rows: "4" %></div>
  </div>

  <div class="form-group field">
    <%= f.label :link1, class: "control-label" %>
    <div><%= f.text_field :link1, class: "form-control" %></div>
  </div>

  <div class="form-group field">
    <%= f.label :link2, class: "control-label" %>
    <div><%= f.text_field :link2, class: "form-control" %></div>
  </div>

  <!-- <div class="field">
    <%= f.label :poll_id %><br>
    <%= f.text_field :poll_id %>
  </div> -->
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate, class: 'btn btn-default btn-raised'  %>
<%= link_to 'Back', :back, class: 'btn btn-default btn-raised'  %>

app/views/candidates/index.html.erb
<div class="jumbotron">
<h1>Listing candidates</h1>

<table width="100%" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Poll</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.description %></td>
        <td><%= candidate.poll.title if candidate.poll   %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<%= link_to 'New Candidate', new_candidate_path, class: 'btn btn-raised' %>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path, class: "btn btn-default btn-raised"  %>

app/views/candidates/show.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @candidate.description %>
</p>

<p>
  <strong>Poll:</strong>
  <%= @candidate.poll.title %>
</p>

<p>
  <strong>Link1:</strong>
  <% if @candidate.link1.present? %>
  <%= link_to @candidate.link1[0, 64] + ' ...', @candidate.link1, target: '_blank' %>
  <% end %>
</p>

<p>
  <strong>Link2:</strong>
  <% if @candidate.link2.present? %>
    <%= link_to @candidate.link2[0, 64] + ' ...', @candidate.link2, target: '_blank' %>
  <% end %>
</p>

</div>
<%= link_to 'Edit', edit_candidate_path(@candidate), class: 'btn btn-default btn-raised' %>
<!-- <%= link_to 'Back', candidates_path %> -->
<%= link_to 'Back', :back, class: 'btn btn-default btn-raised' %>

app/views/election/index.html.erb
<div class="jumbotron">
<h1>Listing polls</h1>

<table width="100%" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start</th>
      <th>End</th>
      <th>Candidates</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.title %></td>
        <td><%= poll.start %></td>
        <td><%= poll.end %></td>
        <td><%= poll.candidates.count %></td>
          <td><%= link_to 'View', election_view_path(poll) %></td>
        <!-- <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/election/view.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>


<p>
  <strong>Poll:</strong>
  <%= @poll.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @poll.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @poll.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @poll.end %>
</p>
</div>

<div class="jumbotron">
  <p>List of Candidates</p>
  <table width="100%" class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Poll</th>
        <!-- <th colspan="3"></th> -->
      </tr>
    </thead>

    <tbody>
      <% @poll.candidates.each do |candidate| %>
        <tr>
          <td><%= candidate.name %></td>
          <td><%= candidate.description %></td>
          <td><%= candidate.poll.title %></td>
          <td><%= link_to 'Show', candidate %></td>
          <td><%= link_to 'Vote', vote_path(candidate, @poll) %></td>
           <!-- <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
          <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/election/vote.html.erb
this is where its voted.  

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>

  <% end %>
<% end %>

app/views/layouts/_nav_items.html.erb
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <b>
       <%= link_to 'Nina', root_path, class: "navbar-brand" %></b>
    </div>
    <div class="navbar-collapse collapse navbar-inverse-collapse">
        <!--
        <form class="navbar-form navbar-left">
            <input type="text" class="form-control col-lg-8" placeholder="Search">
        </form>
-->


        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if current_page?(root_path) %>"> <%= link_to 'Home', root_path %></li>
          <!-- <li class="<%= 'active' if current_page?(root_path) %>"> <%= link_to 'page 1', root_path %></li> -->

          <% if user_signed_in? %>

                <% if current_user.admin? %>
                <li><%= link_to 'Admin', admin_path %></li>
                <li class="dropdown">
                  <%= link_to "admin stuff", "#", :data => {:toggle=>"dropdown"}, :class=>"dropdown-toggle"%>
                  <ul class="dropdown-menu">
                    <li>meh</li>
                  </ul>
                </li>
                <% end %>
                <% if current_user.manager? %>

                    <li class="dropdown">
                      <%= link_to "Manager", "#", :data => {:toggle=>"dropdown"}, :class=>"dropdown-toggle"%>
                      <ul class="dropdown-menu">
                        <li><%= link_to 'Polls', polls_path %></li>
                        <li><%= link_to 'Add Poll', new_poll_path %></li>
                      </ul>
                    </li>
                <% end %>


          <li class="dropdown">
            <%= link_to current_user.login, "#", :data => {:toggle=>"dropdown"}, :class=>"dropdown-toggle"%>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', '#' %></li>
                <li class="divider"></li>
                <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              </ul>
          </li>
          <% else %>
            <li class="<%= 'active' if current_page?(new_user_session_path) %>"> <%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>

        </ul>



    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Election01</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav_items' %>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <div id="flash_notice" class="alert notice fade in" style="display:none"></div>
      <%= render 'layouts/message' %>

      <%= yield %>
    </div>

    <div class="col-lg-3">
      <div class="well sidebar-nav">
        <h3>Links</h3>
        <ul class="nav nav-list">
          <li class="nav-header">Links</li>
          <li><%= link_to "Link 1", "#"  %></li>
          <li><%= link_to "Link 2", "#"  %></li>
          <li>
            <%= link_to "Link 3", "#"  %>
            <ul class="nav nav-list">
              <li><%= link_to "Example link", "#"  %></li>
              <li><%= link_to "Example link", "#"  %></li>
              <li><a href="example link" download>example</a></li>
              <li><a href="example">example</a></li>
            </ul>
          </li>
          <li><%= link_to "Example", "#"  %></li>

        </ul>
      </div><!--/.well -->
    </div><!--/span-->
  </div>

  <footer>

    <p 	>&copy; Copyright 2015 Nina. All Rights Reserved.</p>

    <div>By: <br>
      <div class="g-person" data-href="//plus.google.com/u/0/+ChiragRajkarnikar" data-theme="light" data-layout="landscape" data-showtagline="false" data-showcoverphoto="false" data-rel="author"></div>
      
    </div>
  </footer>

</body>
</html>

app/views/polls/_candidates.html.erb
<div class="jumbotron">
<h1>Listing candidates</h1>

<table width="100%" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Votes</th>
      <!-- <th>Poll</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.description %></td>
        <!-- <td><%= candidate.poll.title %></td> -->
        <td><%= candidate.votes.count %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/polls/_form.html.erb
<div class="jumbotron">
<%= form_for(@poll) do |f| %>
<fieldset>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :title, class: "control-label" %>
    <div><%= f.text_field :title, class: "form-control" %></div>
  </div>
  <div class="form-group field">
    <%= f.label :description, class: "control-label" %>
    <div><%= f.text_area :description, class: "form-control", rows: "4" %></div>
  </div>
  <div class="form-group field">
    <%= f.label :start, class: "control-label"%>
    <div><%= f.datetime_select :start, class: "form-control" %></div>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <%= f.hidden_field :participants, value: 0.0 %>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
</fieldset>
<% end %>
</div>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll, class: "btn btn-default btn-raised" %>
<%= link_to 'Back', polls_path, class: "btn btn-default btn-raised" %>

app/views/polls/index.html.erb
<div class="jumbotron">
<h1>Listing polls</h1>

<table width="100%" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start</th>
      <th>End</th>
      <th>Participants</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.title %></td>
        <td><%= poll.start %></td>
        <td><%= poll.end %></td>
        <td><%= poll.participants %></td>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path, class: "btn btn-secondary" %>
</div>

app/views/polls/new.html.erb
<h1>Add New poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path, class: "btn btn-default btn-flat" %>

app/views/polls/show.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>


<p>
  <strong>Title:</strong>
  <%= @poll.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @poll.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @poll.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @poll.end %>
</p>

<%= link_to 'Add Candidate', new_poll_candidate_path(@poll), class: 'btn  btn-raised' %>
<%= link_to 'Edit', edit_poll_path(@poll), class: 'btn btn-default btn-raised' %>
<%= link_to 'Back', polls_path, class: 'btn btn-default btn-raised' %>
</div>

<%= render 'candidates' %>